### ISSUE TITLE
[teiaddphonetics]: Consider using an alternative to the speech-espeak module

### ISSUE THREAD

**Issue by humenda** [freedict/tools#1]
As can be read on the eSpeak mailing list (and also on Wikipedia), eSpeak is
unmaintained since two years. It would be better to use espeak-ng, which is
largely compatible. I'm not sure whether the Perl module supports a transparent switch to libespeak-ng (there's a compatibility API), but in any case, we really should not start with outdated software :).

**Comment by micha137** [comment]
I actually used espeak-ng with the compat layer... I didn't double check, but expect the API to not have diverted.

**Comment by humenda** [comment]
AFAIK, it has diverted, but there is still the compatibility layer. As long as
you can guarantee that libespeak-ng works fine, there is no need for action.
