### ISSUE TITLE
"pkg-resources=0.0.0" in "requirements.txt"

### ISSUE THREAD

**Issue by Nausx** [freedict/tools#12]
That line was causing me issue. I tried reinstalling and deleting bunch of stuff and only once I decided to remove the line from the `requirement.txt` file, `make mk_venv` worked as expected.

I was still wondering as I couldn't find that package at all. Then I dug deeper to find that, apparently, the line is generated by `pip freeze` when in a *virtualenv* on some systems i.e. *Ubuntu* and *Debian*. It seems those systems separate the `pkg_resources` from `setuptools` and add it as a package. According to that, what I can guess is that there is no special case for `pip freeze` and thus the "package" of `pkg-resources` appears in the resulting output.

https://github.com/pypa/pip/issues/4022
https://github.com/pypa/pip/issues/4668

I don't know if it's the case of who generated the `requirement.txt` file as those bugs are 1y old. But still, as a workaround you can remove that line if you're not using *Debian* or *Ubuntu*.

**Comment by humenda** [comment]
Thanks for the report. It seems as if this was even not strictly required on a
Debian/Ubuntu system, so I remove it. If you find any other issues, let us know.
