### ISSUE TITLE
teiaddphonetics: espeak generates a newline on output for three dots of input

### ISSUE THREAD

**Issue by micha137** [freedict/tools#18]
Example:

```
espeak --ipa "um ... herum"
ˈʌm
 hˈɛɹəm
```

This behaviour breaks teiaddphonetics, which expects exactly one line out output for every line of input.

**Comment by humenda** [comment]
A single colon `:`, three commas `,,,` and ellipsis `…` show the same behaviour.
Does Perl support proper unicode? Python does offer a `.alpha()` method on
characters, valid for *all* alphabetical characters of any language. If it
doesn't, a static list with blacklisted punctuation is also fine.

**Comment by micha137** [comment]
@humenda now catches the exit status in the Makefile and disables phoneme generation if teiaddphonetics aborted with error.  Closing this issue,
