### ISSUE TITLE
Extend tei2slob meta-info parsing capabilities

### ISSUE THREAD

**Issue by humenda** [freedict/tools#2]
`slob info` on a compiled file misses the license information for a few dictionaries, maybe more information for others. It would be great if we could write a script to identify the missing bits and then to gather this information.

I'm opening this issue here, because we can either add this information in our build process  with a script or patch tei2slob. I'd prefer the latter.

Parsing the license information shouldn't be to hard. It's below `availability` and we could search for the full license name + it's abbreviation. Something that works for 95 % of our dictionaries is at
https://anonscm.debian.org/gitweb/?p=pkg-freedict/freedict.git
(there in debian/fetchdictdata.py && grep license).

@karlb If you cannot work on this, please feel free to re-assign me.

Thanks

**Comment by karlb** [comment]
Wouldn't it be better to normalize how the license info is encoded in the TEI files instead of running a license checker when working with those files?

tei2slob currently looks for `<ref target="LICENSE_URL">LICENSE_NAME</ref>` in the `availability` tag. We could add that easily to all our dictionaries and I don't see a downside of it, yet.

Is there any specification how exactly a license should be encoded?

**Comment by humenda** [comment]
I did not yet think about this possibility. Given that we only have 3-5
different licenses, the detection code would be very simple and not force
anybody to use a specific format.

On the other hand, adding a URL to the license is also not a bad idea. It only
means that I need to re-release all dictionaries.

>Is there any specification how exactly a license should be encoded?

No, that is the specific problem :-).

If you opt for using a license URL, I would request that you modify the FreeDict
RNG schema to mandate a `ref` tag and that you update examples in
fd-dictionaries/shared. I'll take care to re-release all dictionaries. That
shouldn't  be too much work, AFAIK.

**Comment by karlb** [comment]
I started working on it:
https://github.com/freedict/fd-dictionaries/tree/license-info-for-slob

How should I deal with texts like these:

> Available under the terms of the GNU General Public License ver. 2.0 and any later version.


What should be the license name?
* GNU General Public License
* GNU General Public License ver. 2.0
* GNU General Public License ver. 2.0 and any later version

What should the link be?
* https://www.gnu.org/licenses/gpl.html
* https://www.gnu.org/licenses/gpl-2.0.html

Maybe choose the first in both cases, since the user is allowed to choose the license version?

**Comment by humenda** [comment]
Thanks for your work.

>How should I deal with texts like these:
>
>> Available under the terms of the GNU General Public License ver. 2.0 and any later version.
I would suggest we tackle the problem like Debian does. They use abbreviations
like lower-casse gfdl, cc-by-sa, lgpl or gpl and if specified a version and an
optional "+". So your example would become "gpl-2+".
This is somewhere hidden on
http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

>What should the link be?
>* https://www.gnu.org/licenses/gpl.html
>* https://www.gnu.org/licenses/gpl-2.0.html
2.0 if it's 2+ and the generic link if not specified.

>Maybe choose the first in both cases, since the user is allowed to choose the license version?
No, 2+ means it's 2 and people can decide whether to upgrade.

**Comment by karlb** [comment]
Using abbreviations does not fit in with the way it's currently used, as the `<ref>` is part of free form availability text and an abbreviation would be hard to understand.

Let's link to https://www.gnu.org/licenses/gpl-2.0.html, then.

Do we keep the text "GNU General Public License ver. 2.0" as currently used in some dictionaries, or do we add "and any later version"?

**Comment by humenda** [comment]
Ok, my bad. Then use the long version and add the any-later-clause, if present
in the text.

**Comment by karlb** [comment]
I've tried to add appropriate refs to all dictionaries except the WikDict ones (which are autogenerated):

https://github.com/freedict/fd-dictionaries/commit/09e2a80f1fba930958631e2fe82be3c752fc4eae

Review welcome! I don't want to accidentally change the license of a dictionary.

Two dictionaries offer a choice between two different licenses. These do not validate and I've not tested the resulting slob license info, yet: eng-pol and eng-ell.

**Comment by humenda** [comment]
Thanks for your work! At a first glance, it looks fine to me. I'll do a more
indepth review when re-releasing the dictionaries, something we ought to do for
slob anyway :).

eng-ell and eng-pol are special indeed, but that is a non-technical problem.
I'll sort that out later.

**Comment by karlb** [comment]
Just for future reference: if we want to standardize short license names we should use the SPDX identifiers from https://spdx.org/licenses/ .

**Comment by humenda** [comment]
Absolutely. I proposed the Debian-copyright fields earlier and they are actually
very close, yet not 100 % compatible. Either is fine.
Would you be so kind to go through the fd-dictionaries and the imported ones to
update the short license name, please?

**Comment by karlb** [comment]
So the results should look like ```Available under the terms of the <ref target="https://www.gnu.org/licenses/gpl-2.0.html">GPL-2.0-or-later</ref>```, right? It does read a bit strange.

**Comment by humenda** [comment]
It does, though it is meant for machines. Is there an attribute of ref or
similar which could be used? Maybe the `<licence>` tag could help? Just to
sketch what I mean:
`<licence target="http://url" title="gpl-2.0-or-later">long version</licence>`.
@bansp thoughts?
