### ISSUE TITLE
convert to csv

### ISSUE THREAD

**Issue by theDigitalMaster** [freedict/tools#22]
Hello,

how to convert freedict like 

https://github.com/freedict/fd-dictionaries/tree/master/deu-eng

to scv file?

**Comment by humenda** [comment]
This depends on your specific use case. CSV is not a well-specified format, but
you could use python's etree module and extract the "orth", "quote" and
"gramGrp" lements. Any other language will do the job as well. If you could
described what you are trying to achieve, we can maybe help more specifically.

**Comment by karlb** [comment]
xmlstarlet is also useful for tasks like this. See
https://www.joyofdata.de/blog/transforming-xml-document-into-csv-using-xmlstarlet/

**Comment by theDigitalMaster** [comment]
hello again and thank you for your reply(s)

I want to convert in a simple csv. Imagine an excel spreadsheet with the first row the source language words, second row the 1st translation, third row the 2nd translation and so on.

**Comment by bansp** [comment]
You can use XSLT to dump the contents. It's a simple conversion from a very regular format, so you can use that as an opportunity to quickly get to grips with the language.

**Comment by theDigitalMaster** [comment]
And how do I make the conversion? The XSLT is just a  styling language for XML.

**Comment by theDigitalMaster** [comment]
https://github.com/freedict/fd-dictionaries/blob/master/deu-eng/deu-eng.tei

I tried using python and etree but I am begginer in programming.
Using

```
import xml.etree.ElementTree as ET
tree = ET.parse('c:\deu-eng.tei')
root = tree.getroot()
```

I can load the file in python.
Here is a chunck from the .tei file:

      ```
<entry>
        <form>
          <orth>Reklamation</orth>
          <pron>reːklamatsiːoːn</pron>
        </form>
        <gramGrp>
          <pos>n</pos>
          <num>s</num>
        </gramGrp>
        <sense>
          <cit type="trans">
            <quote>complain</quote>
          </cit>
        </sense>
      </entry>
```

and this:
     ```
 <entry>
        <form>
          <orth>Reklame</orth>
          <pron>reːklaːmə</pron>
        </form>
        <gramGrp>
          <pos>n</pos>
          <num>s</num>
        </gramGrp>
        <sense>
          <cit type="trans">
            <quote>advertisement</quote>
          </cit>
          <cit type="trans">
            <quote>advertising</quote>
          </cit>
          <cit type="trans">
            <quote>billing</quote>
          </cit>
        </sense>
      </entry>
```

the first has one translation, the second has three translation. I want to extract the "orth" and the firtst translation for start. Can someone provide a example in python?

**Comment by humenda** [comment]
Hi

>I tried using python and etree but I am begginer in programming.
>Using
>
>```
>import xml.etree.ElementTree as ET
>tree = ET.parse('c:\deu-eng.tei')
>root = tree.getroot()
>```
Unfortunately, we do not have the capacity to help you learn Python, but you
should be able to find help in the official Python forum:
https://www.python.org/community/forums

In any case, here's a working code snippet with a few explanations:

```
import xml.etree.ElementTree as ET
tree = ET.parse('deu-eng.tei')

# The TEI file has namespaces. Use the "tei" prefix to shorten the queries.
NS = {'tei': 'http://www.tei-c.org/ns/1.0'}

root = tree.getroot()
# find an entry at any depth ".//tei:entry"):
for entry in root.findall('.//tei:entry', NS):##'tei:TEI/tei:text/tei:body', NS):
    # find first occurrence of orth within entry
    orth = entry.find('.//tei:orth', NS)
    print(orth.text)
```
