### ISSUE TITLE
Use PyGlossary for additional export formats

### ISSUE THREAD

**Issue by karlb** [freedict/tools#24]
The project looks like an excellent fit in our quest to support more output formats:

* It already supports multiple interesting output formats
* It is written in python, so it fits in well with other tooling we currently have and we can do changes if necessary
* It already supports FreeDict TEI as output (although not as input yet)
* The project developer was very responsive and helpful in my request to support Kobo dicts

I just got a FreeDict dictionary working on my Kobo e-reader by converting one of our .slob files into the Kobo dict format using [PyGlossary](https://github.com/ilius/pyglossary). See https://github.com/ilius/pyglossary/issues/205. This is a good indicator that going this route is feasible and has a good reward/effort ratio.

**Comment by humenda** [comment]
We suupport pyglossary now to convert to StarDict. I'll close the issue hence.
For particular formats, we should open an issue per format type that we would
like to add.
