### ISSUE TITLE
teiaddphonetics fails on  certain combinations of interpunctuation

### ISSUE THREAD

**Issue by respiranto** [freedict/tools#25]
When any `<orth>` element contains a sequence matching any of the below regexes, teiaddphonetics fails.

```
[[:alphanum:]].*[!?:,]["']
[[:alphanum:]].*[;:]\)
[[:alphanum:]].*[;:!?,][\[\]{}(]
```

Corresponding examples are (in order):
* `"Angeklagter!"` (minimal: `x!"`)
* `(anyword:)` (minimal: `x:)`) -- *does not occur in practice*
* `N:(D2Ln)` (minimal: `x:(`)

These issues were found when feeding an initial version of the newly Ding-imported deu-eng dictionary.
See also the corresponding [thread on the ML](https://www.freelists.org/post/freedict/Poll-replace-deueng-engdeu,36).

A corresponding minimal TEI XML tree (for the first example) would like follows (note that `"` is usually encoded as `&quot;`):
```
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="freedict-dictionary.xsl"?>
<?xml-stylesheet type="text/css" href="freedict-dictionary.css"?>
<?oxygen SCHSchema="freedict-P5.rng"?>
<?oxygen RNGSchema="freedict-P5.rng" type="xml"?>
<!DOCTYPE TEI SYSTEM "freedict-P5.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0" version="5.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title></title>
      </titleStmt>
      <editionStmt>
        <edition></edition>
      </editionStmt>
      <publicationStmt>
        <publisher></publisher>
      </publicationStmt>
      <sourceDesc>
        <p></p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <entry>
        <form>
          <orth>&quotAngeklagte!&quot;</orth>
        </form>
      </entry>
    </body>
  </text>
</TEI>
```

**Comment by humenda** [comment]
Thanks for the report.
This is now WIP by me. I'll expect to have a version in the upcoming days.

**Comment by humenda** [comment]
On branch teiaddphonetics_rewrite, I have prepared a completely rewritten version that fixes both the teiaddphonetics failure and the memory consumption issue.
