### ISSUE TITLE
add support for the Stardict format as output format

### ISSUE THREAD

**Issue by karlb** [freedict/tools#5]
Stardict is a widely used format and is hence worth supporting. There's also a
mobile client QDict available which understands this format. Since we don't have a client, it'd be great to make our dictionaries available this way.

(Moved from https://github.com/freedict/fd-dictionaries/issues/11, please view previous discussion there)

**Comment by humenda** [comment]
I and Micha137 discussed that it is not worth supporting this forat. It seems as development of StarDict has finally ceased. With the support of the Slob format, we have an actively maintained and modern alternative, both for mobile and desktop.
