### ISSUE TITLE
Add support for the DictionaryForMID format

### ISSUE THREAD

**Issue by karlb** [freedict/tools#6]
DictionaryForMID is a dictionary program featuring a custom format, importer
scripts and also an Android client.
Documentation seems good and both authors of the desktop / mobile version are
active. Their architecture model is described here:
<http://dictionarymid.sourceforge.net/development.html>.

For the short term, we could easily leverage their dictd2dictionaryformid
conversion process, see
<http://dictionarymid.sourceforge.net/DfM-Creator/index.html> and the GUI
<http://dictionarymid.sourceforge.net/DfM-Creator/gui-DictdToDictionaryForMIDs.html>.

For the longer term, I'd like to create template overrides for our style sheets
which would format certain parts of our format differently, so that we could
make use of the formatting features of the DictionaryForMID format. For
instance, example sentences can be formatted separately. That is ideally not to
much effort, since the format in use is quite close to the dictd format, see
<http://dictionarymid.sourceforge.net/faq.html>.

Last but not least, the project features its own API to inform about new
dictionaries and more importantly, to push the dictionaries to mobile devices.
See <http://dictionarymid.sourceforge.net/ota.php?p=1>.

I would like to see this format supported and would love to integrate our
FreeDict API into DictionaryForMID, so that we don't replicate efforts.

(Moved from https://github.com/freedict/fd-dictionaries/issues/13, please view previous discussion there)

**Comment by humenda** [comment]
At the moment, we do not plan to support DictionaryForMIDs. With the support for
slob, we have a modern alternative and we have not enough capacity TM to write
another exporter. That said, DictionaryForMIDs also doesn't look *very* active
anymore. If you feel that's not right, you are welcome to start working on this.
